server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?userUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.myHospital.hospital.entity

