server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?userUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.myHospital.hospital.entity

